export const devDeps = [
  '@istanbuljs/nyc-config-typescript',
  '@types/benchmark',
  '@types/chai',
  '@types/cli-table2',
  '@types/mocha',
  'auto-changelog',
  'benchmark',
  'chai',
  'cli-table2',
  'del-cli',
  'fast-memoize',
  'logdown',
  'microtime',
  'mocha',
  'nyc',
  'ora',
  'ts-node',
  'tslint',
  'typedoc',
  'typescript',
]

export const webpackDeps = [
  'clean-webpack-plugin',
  'awesome-typescript-loader',
  'html-webpack-plugin',
  'mini-css-extract-plugin',
  'webpack-dev-server',
  'css-loader',
  'dotenv-webpack',
  'style-loader',
  'webpack',
  'webpack-cli',
]
